# Generated by Django 2.1 on 2018-10-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('timestamp', models.TimeField()),
                ('data', models.TextField()),
                ('previous_hash', models.CharField(max_length=64)),
                ('self_hash', models.CharField(max_length=64)),
            ],
        ),
    ]
